# Form implementation generated from reading ui file 'c:\Users\Abdalhalim\OneDrive\Documents\VS Code\Python\SARC-Data-System\QtDesigner\representative.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_newRepresentativeDialog(object):
    def setupUi(self, newRepresentativeDialog):
        newRepresentativeDialog.setObjectName("newRepresentativeDialog")
        newRepresentativeDialog.setMinimumSize(QtCore.QSize(500, 235))
        newRepresentativeDialog.setMaximumSize(QtCore.QSize(500, 235))
        font = QtGui.QFont()
        font.setFamily("Almarai")
        font.setPointSize(10)
        newRepresentativeDialog.setFont(font)
        newRepresentativeDialog.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        newRepresentativeDialog.setLocale(QtCore.QLocale(QtCore.QLocale.Language.Arabic, QtCore.QLocale.Country.Syria))
        self._2 = QtWidgets.QVBoxLayout(newRepresentativeDialog)
        self._2.setObjectName("_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(newRepresentativeDialog)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.txtArea = QtWidgets.QLineEdit(newRepresentativeDialog)
        self.txtArea.setMaxLength(15)
        self.txtArea.setObjectName("txtArea")
        self.horizontalLayout_2.addWidget(self.txtArea)
        self.label_5 = QtWidgets.QLabel(newRepresentativeDialog)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.txtSubArea = QtWidgets.QLineEdit(newRepresentativeDialog)
        self.txtSubArea.setMaxLength(15)
        self.txtSubArea.setObjectName("txtSubArea")
        self.horizontalLayout_2.addWidget(self.txtSubArea)
        self._2.addLayout(self.horizontalLayout_2)
        self.gridlayout = QtWidgets.QGridLayout()
        self.gridlayout.setObjectName("gridlayout")
        spacerItem = QtWidgets.QSpacerItem(0, 15, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.gridlayout.addItem(spacerItem, 3, 1, 1, 1)
        self.label = QtWidgets.QLabel(newRepresentativeDialog)
        self.label.setObjectName("label")
        self.gridlayout.addWidget(self.label, 2, 0, 1, 1)
        self.txtPhoneNumber = QtWidgets.QLineEdit(newRepresentativeDialog)
        self.txtPhoneNumber.setMaxLength(10)
        self.txtPhoneNumber.setObjectName("txtPhoneNumber")
        self.gridlayout.addWidget(self.txtPhoneNumber, 2, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(newRepresentativeDialog)
        self.label_2.setObjectName("label_2")
        self.gridlayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.txtRepresentative = QtWidgets.QLineEdit(newRepresentativeDialog)
        self.txtRepresentative.setMaxLength(35)
        self.txtRepresentative.setObjectName("txtRepresentative")
        self.gridlayout.addWidget(self.txtRepresentative, 0, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(newRepresentativeDialog)
        self.label_6.setObjectName("label_6")
        self.gridlayout.addWidget(self.label_6, 1, 0, 1, 1)
        self.txtID = QtWidgets.QLineEdit(newRepresentativeDialog)
        self.txtID.setMaxLength(11)
        self.txtID.setObjectName("txtID")
        self.gridlayout.addWidget(self.txtID, 1, 1, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(newRepresentativeDialog)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridlayout.addWidget(self.buttonBox, 4, 1, 1, 1)
        self._2.addLayout(self.gridlayout)

        self.retranslateUi(newRepresentativeDialog)
        self.buttonBox.accepted.connect(newRepresentativeDialog.accept)
        self.buttonBox.rejected.connect(newRepresentativeDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(newRepresentativeDialog)
        newRepresentativeDialog.setTabOrder(self.txtArea, self.txtSubArea)
        newRepresentativeDialog.setTabOrder(self.txtSubArea, self.txtRepresentative)
        newRepresentativeDialog.setTabOrder(self.txtRepresentative, self.txtID)
        newRepresentativeDialog.setTabOrder(self.txtID, self.txtPhoneNumber)

    def retranslateUi(self, newRepresentativeDialog):
        _translate = QtCore.QCoreApplication.translate
        newRepresentativeDialog.setWindowTitle(_translate("newRepresentativeDialog", "إضافة مندوب جديد"))
        self.label_3.setText(_translate("newRepresentativeDialog", "القرية:"))
        self.label_5.setText(_translate("newRepresentativeDialog", "الحي:"))
        self.label.setText(_translate("newRepresentativeDialog", "رقم الهاتف:"))
        self.label_2.setText(_translate("newRepresentativeDialog", "اسم المندوب:"))
        self.label_6.setText(_translate("newRepresentativeDialog", "رقم الهويّة:"))
