# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'loginWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_loginWindow(object):
    def setupUi(self, loginWindow):
        loginWindow.setObjectName("loginWindow")
        loginWindow.resize(380, 600)
        loginWindow.setMinimumSize(QtCore.QSize(380, 600))
        loginWindow.setMaximumSize(QtCore.QSize(380, 600))
        font = QtGui.QFont()
        font.setFamily("Almarai")
        font.setPointSize(10)
        loginWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("login.svg"),
                       QtGui.QIcon.Normal, QtGui.QIcon.Off)
        loginWindow.setWindowIcon(icon)
        loginWindow.setLayoutDirection(QtCore.Qt.RightToLeft)
        loginWindow.setLocale(QtCore.QLocale(
            QtCore.QLocale.Arabic, QtCore.QLocale.Syria))
        self.widget = QtWidgets.QWidget(loginWindow)
        self.widget.setObjectName("widget")
        self.vboxlayout = QtWidgets.QVBoxLayout(self.widget)
        self.vboxlayout.setObjectName("vboxlayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setEnabled(True)
        self.label.setMinimumSize(QtCore.QSize(250, 250))
        self.label.setMaximumSize(QtCore.QSize(250, 250))
        self.label.setSizeIncrement(QtCore.QSize(0, 0))
        self.label.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label.setPixmap(QtGui.QPixmap("assets/logo/SARC Logo HD.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.vboxlayout.addWidget(self.label, 0, QtCore.Qt.AlignHCenter)
        spacerItem = QtWidgets.QSpacerItem(
            20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.vboxlayout.addItem(spacerItem)
        self.label_2 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Almarai")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.vboxlayout.addWidget(self.label_2)
        self.lineEdit = QtWidgets.QLineEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        self.lineEdit.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Almarai")
        font.setPointSize(10)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.vboxlayout.addWidget(self.lineEdit)
        self.label_3 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Almarai")
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.vboxlayout.addWidget(self.label_3)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.lineEdit_2.sizePolicy().hasHeightForWidth())
        self.lineEdit_2.setSizePolicy(sizePolicy)
        self.lineEdit_2.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Almarai")
        font.setPointSize(10)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.vboxlayout.addWidget(self.lineEdit_2)
        spacerItem1 = QtWidgets.QSpacerItem(
            10, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.vboxlayout.addItem(spacerItem1)
        self.btnLogin = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("Almarai")
        font.setPointSize(10)
        self.btnLogin.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("assets/icons/login.svg"),
                        QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnLogin.setIcon(icon1)
        self.btnLogin.setAutoDefault(True)
        self.btnLogin.setDefault(True)
        self.btnLogin.setObjectName("btnLogin")
        self.vboxlayout.addWidget(self.btnLogin)
        self.btnAccountsManage = QtWidgets.QCommandLinkButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.btnAccountsManage.setFont(font)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(
            "assets/icons/business-manager.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnAccountsManage.setIcon(icon2)
        self.btnAccountsManage.setIconSize(QtCore.QSize(25, 25))
        self.btnAccountsManage.setObjectName("btnAccountsManage")
        self.vboxlayout.addWidget(self.btnAccountsManage)
        spacerItem2 = QtWidgets.QSpacerItem(
            20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.vboxlayout.addItem(spacerItem2)
        loginWindow.setCentralWidget(self.widget)

        self.retranslateUi(loginWindow)
        self.btnLogin.clicked.connect(loginWindow.close)
        QtCore.QMetaObject.connectSlotsByName(loginWindow)

    def retranslateUi(self, loginWindow):
        _translate = QtCore.QCoreApplication.translate
        loginWindow.setWindowTitle(_translate(
            "loginWindow", "نافذة تسجيل الدخول"))
        self.label_2.setText(_translate("loginWindow", "اسم المُستخدم:"))
        self.label_3.setText(_translate("loginWindow", "كلمة السر"))
        self.btnLogin.setText(_translate("loginWindow", "تسجيل الدخول"))
        self.btnLogin.setShortcut(_translate("loginWindow", "Return"))
        self.btnAccountsManage.setToolTip(_translate(
            "loginWindow", "هذا الزر مُخصص لمسؤول البيانات"))
        self.btnAccountsManage.setText(_translate(
            "loginWindow", "إدارة حسابات مُدخلي البيانات"))
